### ISSUE TITLE
Balance not showing correctly.

### ISSUE THREAD

**Issue by benthecarman** [futurepaul/fluttermint#69]
I got 69 sats from the faucet however my balance is not updated. 

I tried going to the receive tab and creating a new invoice and that did not update my balance. 

Minor note: the Paid is confusing for a receive. Not sure if I was paid or if I paid someone else. 

![image](https://user-images.githubusercontent.com/15256660/191812800-14c8e9e8-d705-44b4-9827-af17ab90b44f.png)

**Comment by justinmoon** [comment]
Which version are you using?

**Comment by justinmoon** [comment]
I think this was fixed by https://github.com/fedimint/fedimint/pull/607. So try again on the newest TestFlight and let us know if it continues

**Comment by benthecarman** [comment]
Updated to the 0.7 testflight that was released and still seeing the error. Maybe I need to receive again?

**Comment by benthecarman** [comment]
After receiving a payment my balance now shows correctly
